db = db.getSiblingDB('m165_quiz');

db.createUser({
  user: 'quiz_admin',
  pwd: 'werwirdmillionaer',
  roles: [
    {
      role: 'readWrite',
      db: 'm165_quiz',
    },
  ],
});

db.createCollection('questions');
db.createCollection('quizzes');
db.createCollection('games');

db.quizzes.insertMany([
  {
    "_id": new ObjectId("63877b982bd515acf41f4743"),
    "name": "Software Engineer Quiz",
    "createdBy": "Noah G. (Nevah5)",
    "createdOn": 1669876220,
    "tags": [
      "programming",
      "code",
      "software",
      "computer"
    ]
  },
  {
    "_id": new ObjectId("638867df7af39a86ab5e23c1"),
    "name": "Autos Quiz",
    "createdBy": "Noah G. (Nevah5)",
    "createdOn": 1669880300,
    "tags": [
      "cars",
      "autos",
      "ferrari",
      "lamborghini",
    ]
  },
  {
    "_id": new ObjectId("6388690a7af39a86ab5e23c2"),
    "name": "Language Quiz",
    "createdBy": "Noah G. (Nevah5)",
    "createdOn": 1669880564,
    "tags": [
      "language",
      "life",
    ],
  },
]);
db.questions.insertMany([
  {
    "n": 1,
    "quizId": "63877b982bd515acf41f4743",
    "q": "What is VSC?",
    "a1": "Visual Slider Collision",
    "a2": "Very Silly Code",
    "a3": "Visual Studio Code",
    "a4": "Vamos Siuuuu Christiano",
    "c": 3,
  },
  {
    "n": 2,
    "quizId": "63877b982bd515acf41f4743",
    "q": "How many times should you commit?",
    "a1": "after every character",
    "a2": "after a small part of code",
    "a3": "every day",
    "a4": "after a feature or bugfix",
    "c": 4,
  },
  {
    "n": 3,
    "quizId": "63877b982bd515acf41f4743",
    "q": "PHP...",
    "a1": "...is a script-language.",
    "a2": "...is ran in the browser.",
    "a3": "...is barely used anymore.",
    "a4": "...is reactive.",
    "c": 1,
  },
  {
    "n": 4,
    "quizId": "63877b982bd515acf41f4743",
    "q": "MongoDB is like...",
    "a1": "...MariaDB.",
    "a2": "...Firebase Firestore.",
    "a3": "...SQL.",
    "a4": "...Financing.",
    "c": 2,
  },
  {
    "n": 5,
    "quizId": "63877b982bd515acf41f4743",
    "q": "What is the largest cloud provider?",
    "a1": "...Google Cloud.",
    "a2": "...Redhat.",
    "a3": "...AWS.",
    "a4": "...Azure.",
    "c": 3,
  },
  {
    "n": 6,
    "quizId": "63877b982bd515acf41f4743",
    "q": "How can you close vim?",
    "a1": "Escape Key, then type ':qw' and press Enter",
    "a2": "CTRL + W",
    "a3": "Escape Key, then type ':sw' and press Enter",
    "a4": "Escape Key, then type ':wq' and press Enter",
    "c": 4,
  },
  {
    "n": 7,
    "quizId": "63877b982bd515acf41f4743",
    "q": "How many devices run Java?",
    "a1": "More than 15 Billion",
    "a2": "More than 3 Billion",
    "a3": "Around 40 Billion",
    "a4": "893 Million",
    "c": 1,
  },
  {
    "n": 8,
    "quizId": "63877b982bd515acf41f4743",
    "q": "As a developer I'm your eyes, showing you the result of your code in your language of choice. What am I?",
    "a1": "Print statement",
    "a2": "Stack trace",
    "a3": "Your chosen language",
    "a4": "Code comments",
    "c": 1,
  },
  {
    "n": 9,
    "quizId": "63877b982bd515acf41f4743",
    "q": "I'm sent before I'm ready, I'll break before you know it and you can't find me many places. What am I?",
    "a1": "An alpha release",
    "a2": "A testing feature",
    "a3": "A bug",
    "a4": "A beta release",
    "c": 4,
  },
  {
    "n": 10,
    "quizId": "63877b982bd515acf41f4743",
    "q": "I provide you with information, like a 'waiter'. What am I?",
    "a1": "An API",
    "a2": "A server",
    "a3": "A stack trace",
    "a4": "A harddisk",
    "c": 2,
  },
  {
    "n": 11,
    "quizId": "63877b982bd515acf41f4743",
    "q": "What is the most used tool for software engineers?",
    "a1": "GitHub",
    "a2": "StackOverflow",
    "a3": "Git",
    "a4": "NodeJs",
    "c": 2,
  },
  {
    "n": 12,
    "quizId": "63877b982bd515acf41f4743",
    "q": "What is a URL?",
    "a1": "the uno relation list",
    "a2": "A unified resource location",
    "a3": "A unified resource locator",
    "a4": "the us resource listings",
    "c": 3,
  },
  {
    "n": 13,
    "quizId": "63877b982bd515acf41f4743",
    "q": "Appian is a corporation from...",
    "a1": "...Canada.",
    "a2": "...the USA.",
    "a3": "...Germany.",
    "a4": "...Switzerland.",
    "c": 2,
  },
  {
    "n": 14,
    "quizId": "63877b982bd515acf41f4743",
    "q": "What is the oldest programming language?",
    "a1": "Fortran",
    "a2": "Assembly",
    "a3": "C",
    "a4": "Cobol",
    "c": 2,
  },
  {
    "n": 15,
    "quizId": "63877b982bd515acf41f4743",
    "q": "When was the \"first appearance\" of Assembly?",
    "a1": "1950",
    "a2": "1944",
    "a3": "1947",
    "a4": "1965",
    "c": 3,
  },
]);
